# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPlayandPauseButton():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_playandPauseButton(self):
    # Test name: Play and Pause Button
    # Step # | name | target | value
    # 1 | open | https://music.youtube.com/explore | 
    self.driver.get("https://music.youtube.com/explore")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | runScript | window.scrollTo(0,192.67747497558594) | 
    self.driver.execute_script("window.scrollTo(0,192.67747497558594)")
    # 4 | click | css=.style-scope:nth-child(1) > .left-items .icon | 
    self.driver.find_element(By.CSS_SELECTOR, ".style-scope:nth-child(1) > .left-items .icon").click()
    # 5 | click | css=#play-pause-button > #icon | 
    self.driver.find_element(By.CSS_SELECTOR, "#play-pause-button > #icon").click()
    # 6 | click | css=#play-pause-button > #icon | 
    self.driver.find_element(By.CSS_SELECTOR, "#play-pause-button > #icon").click()
    # 7 | close |  | 
    self.driver.close()
  
